AllCops:
  Excludes:
    - db/schema.rb

Documentation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false
